# Generated by Django 5.2.1 on 2025-05-12 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LugarTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(choices=[('restaurante', 'Restaurante'), ('atraccion', 'Atracción'), ('hospedaje', 'Hospedaje')], max_length=20)),
                ('direccion', models.CharField(max_length=200)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('imagen_principal', models.ImageField(blank=True, null=True, upload_to='lugares/')),
                ('calificacion_promedio', models.FloatField(default=0)),
            ],
        ),
    ]
